<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="1" total="4" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="test-parameter" duration-ms="1996" started-at="2022-08-01T05:35:55Z" finished-at="2022-08-01T05:35:57Z">
    <groups>
    </groups>
    <test name="examplel" duration-ms="1996" started-at="2022-08-01T05:35:55Z" finished-at="2022-08-01T05:35:57Z">
      <class name="com.hxk.tesngDemo.TestDemo">
        <test-method status="PASS" signature="test1()[pri:0, instance:com.hxk.tesngDemo.TestDemo@4e4aea35]" name="test1" duration-ms="2" started-at="2022-08-01T05:35:56Z" finished-at="2022-08-01T05:35:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1 -->
      </class> <!-- com.hxk.tesngDemo.TestDemo -->
      <class name="com.hxk.tesngDemo.courseRecord404">
        <test-method status="FAIL" signature="wo404()[pri:0, instance:com.hxk.tesngDemo.courseRecord404@6e2c9341]" name="wo404" duration-ms="1335" started-at="2022-08-01T05:35:55Z" finished-at="2022-08-01T05:35:56Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[服务器返回的状态码不是200 expected [200] but found [404]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 服务器返回的状态码不是200 expected [200] but found [404]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at com.hxk.tesngDemo.courseRecord404.wo404(courseRecord404.java:33)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:110)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- wo404 -->
      </class> <!-- com.hxk.tesngDemo.courseRecord404 -->
      <class name="com.hxk.tesngDemo.index">
        <test-method status="PASS" signature="index()[pri:0, instance:com.hxk.tesngDemo.index@32464a14]" name="index" duration-ms="414" started-at="2022-08-01T05:35:56Z" finished-at="2022-08-01T05:35:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- index -->
      </class> <!-- com.hxk.tesngDemo.index -->
    </test> <!-- examplel -->
  </suite> <!-- test-parameter -->
</testng-results>
